version: "3.9"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=christopherallison
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=graphql_api
    ports:
      - 5434:5434

  security_converter:
    build:
      # dockerfile: "Dockerfile"
      # dockerfile: "Dockerfile.simple"
      dockerfile: "Dockerfile.slim"
      context: .
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - DATABASE_URL=postgres://christopherallison:12345@db/graphql_api?sslmode=disable
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8080:8080

