apiVersion: v1
kind: Namespace
metadata:
  name: security-converter
  labels:
    name: security-converter
    environment: production
    classification: controlled
    owner: dnd
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: security-converter-quota
  namespace: security-converter
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "2"
    count/pods: "10"
    count/services: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: security-converter-limits
  namespace: security-converter
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: security-converter
  labels:
    app: postgres
    component: database
type: Opaque
data:
  # Base64 encoded values (replace with actual values):
  # christopherallison
  POSTGRES_USER: Y2hyaXN0b3BoZXJhbGxpc29u
  # 12345
  POSTGRES_PASSWORD: MTIzNDU=
  # graphql_api (matches docker-compose.yml)
  POSTGRES_DB: Z3JhcGhxbF9hcGk=
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: security-converter
  labels:
    app: api
    component: application
type: Opaque
data:
  # Base64 encoded values (replace with actual secure values):
  # postgres://christopherallison:12345@postgres-service:5432/graphql_api?sslmode=disable
  DATABASE_URL: cG9zdGdyZXM6Ly9jaHJpc3RvcGhlcmFsbGlzb246MTIzNDVAcG9zdGdyZXMtc2VydmljZTo1NDMyL2dyYXBocWxfYXBpP3NzbG1vZGU9ZGlzYWJsZQo=
  # 32CHARSECRETKEY (replace with actual 32-char key)
  SECRET_KEY: MzJDSEFSU0VDUkVUS0VZ
  # 32CHARSECRETKEY (replace with actual 32-char key)
  PASSWORD_SECRET_KEY: MzJDSEFSU0VDUkVUS0VZ
  # 32CHARSECRETKEY (replace with actual 32-char key)
  JWT_SECRET_KEY: MzJDSEFSU0VDUkVUS0VZ
  # some_admin@email.com
  ADMIN_EMAIL: c29tZV9hZG1pbkBlbWFpbC5jb20=
  # ADMINPASSWORD (replace with actual secure password)
  ADMIN_PASSWORD: QURNSU5QQVNTV09SRA==
  # Admin Name
  ADMIN_NAME: QWRtaW4gTmFtZQ==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: security-converter
  labels:
    app: api
    component: application
data:
  HOST: "0.0.0.0"
  PORT: "8080"
  ENVIRONMENT: "production"
  RUST_LOG: "info"