# Security Converter API Deployment for DND Private Environment
# Uses private Artifact Registry image instead of external DockerHub

apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
data:
  HOST: "0.0.0.0"
  PORT: "8080"
  DATABASE_URL: "postgres://christopherallison:12345@postgres-service/security_classification_converter?sslmode=disable"
  SECRET_KEY: "32CHARSECRETKEY12345678901234567890"
  PASSWORD_SECRET_KEY: "32CHARSECRETKEY12345678901234567890"
  JWT_SECRET_KEY: "32CHARSECRETKEY12345678901234567890"
  ADMIN_EMAIL: "admin@dnd.ca"
  ADMIN_PASSWORD: "SecureAdminPass123!"
  ADMIN_NAME: "DND Administrator"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          # IMPORTANT: This uses your private Artifact Registry image
          image: northamerica-northeast1-docker.pkg.dev/admds-edip-datasandbox/security-converter-repo/security-converter:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: api-configmap
          # Health checks optimized for NATO security app
          startupProbe:
            failureThreshold: 60  # Wait up to 10 minutes for startup
            periodSeconds: 10
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - name: http
      port: 8080
      targetPort: http
  type: ClusterIP